language: python

python:
  - "3.6"

install:
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - wget -nc https://dl.winehq.org/wine-builds/Release.key
  - sudo apt-key add Release.key
  - sudo apt-get update
  - sudo apt-get install unzip
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - sudo apt-get install --install-recommends winehq-stable
  - wget http://www.cs.unc.edu/~isenburg/lastools/download/LAStools.zip -O lastools.zip
  - unzip -q lastools.zip -x "LAStools/*toolbox/*" "LAStools/example*/*" "LAStools
/src/*" "LAStools/data/*" -d $HOME
  - wget http://forsys.sefs.uw.edu/Software/FUSION/fusionlatest.zip -O fusion.zip
  - unzip -q fusion.zip -x "APScripts/*" -d $HOME/fusion
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda env create --quiet --name pyFIRS --file environment.yml
  - source activate pyFIRS
  - python setup.py install

script:
  - python ./pyFIRS/tests/test.py
