language: python

python:
  - "3.6"

install:
  - sudo apt-get update
  - sudo apt-get install unzip
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - wget http://www.cs.unc.edu/~isenburg/lastools/download/LAStools.zip -O lastools.zip
  - unzip -q lastools.zip -d $HOME
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update --quiet conda
  - conda info --all
  - conda env create --quiet --name pyFIRS --file environment.yml
  - source activate pyFIRS
  - python setup.py install

script:
  - python ./pyFIRS/tests/test.py
